language: python
python:
- '2.7'
env:
  global:
  - secure: DypK3rEVbtnMLbDZJr9hOAGwJwdXErE1xs+2HFSjs4wTkMa/Run/SWiAeRKarQWhTpaqgIigwBWR0o48RuDP+2I0/LGKX15rXaqRdT8fa7TwvHbcMmawgqn8yWz/XMNDV3cFs73nXJA/zK/Payff7o4jkIN1vWjW3HFuo32HtEM=
install: pip install -r requirements.txt
script:
  - coverage run --source=. manage.py test -v 2
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  api_key:
    secure: bK5Wp0bTkv5LceRzIJjZntTKHbed70oLoMNaRv4sr8pkCKZQtVUmqmXMNsvihm49tU0nM9sVJCmb6HwcEX+1Nl9aeE0dJOi1zQC8ppNALNaHza77yGYW5aABQk9zq+xUW0w1BxxnN/6ysUzCsqQjvE2dIMDXt5Y01Cy3494AjJ8=
  app:
    development: wasa2il-staging
